server:
  port: 0
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

spring:
  application:
    name: user-service
  r2dbc:
    url: r2dbc:h2:mem:///user
    username: sa
    password:
logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG
kafka:
  consumer:
    bootstrap-servers: {kafka-server-ip}:9092
    group-id: group_id
    auto-offset-reset: earliest
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  producer:
    bootstrap-servers: {kafka-server-ip}:9092
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer
